services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "0.0.0.0:1883:1883"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
    networks:
      - backend-net

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    env_file:
      - .env
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - backend-net

  telegraf:
    image: telegraf:1.29
    env_file:
      - .env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - backend-net

  grafana:
    image: grafana/grafana:10.0.0
    ports:
      - "3000:3000"
    networks:
      - backend-net
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_ORG=${DOCKER_INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${DOCKER_INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}

networks:
  backend-net:
    driver: bridge

volumes:
  mosquitto-data:
  influxdb-data:
  grafana-data:
